# Site settings
title: tirefi.re
email: tirefire@tirefi.re
description: > 
  Tires are not prone to self-ignition as a tire must be heated to at least 400 °C (750 °F) for a period of several minutes prior to ignition.
baseurl: "" 
url: "https://tirefi.re"
twitter_username: tirefirebot
github_username: misfitdev

emptyArray: []

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      webring: true

# Build settings - GitHub Pages compatible
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-github-metadata

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html

# GitHub Pages settings
repository: misfitdev/tirefi.re

# Include dotfiles and directories that Jekyll normally ignores
include:
  - .wip

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
  - .travis.yml
  - docker-compose.yml
  - Makefile

# Analytics
google_analytics_tracking_id: UA-79918240-1
